{{- if .Values.postgresql.internal.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: {{ .Values.service.db.type }}
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
{{- end }}
